image: ubuntu:16.04

stages:
  - build

builddebpisak:
  stage: build
  before_script:
    - apt-get -qq update
    - apt-get -qq -y install git debhelper sed equivs chrpath python3-all python3-pip > /dev/null
    - apt-get -qq -y install python-dev > /dev/null
    - pip3 install stdeb
  script:
    - ./debbuildpisak.sh
  artifacts:
    name: "{$CI_BUILD_NAME_$CI_BUILD_REF_NAME}"
    paths:
    - ./dist/*.deb

